---
apiVersion: v2
name: node-local-dns
version: 2.7.0
appVersion: 1.26.8
home: https://github.com/lablabs/k8s-nodelocaldns-helm
description: NodeLocal DNS Cache helm chart
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.svg
keywords:
  - node
  - dns
  - cache
  - kubernetes
sources:
  - https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/nodelocaldns
maintainers:
  - name: martinhaus
  - name: haad
engine: gotpl
type: application
annotations:
  artifacthub.io/changes: |
    - Support the VERIFY_TIMEOUT argument of cache.serve_stale
    - Bump k8s-dns-node-cache to 1.26.8
    - Track the node-cache image with Renovate
